export const propertiesToInclude = [
    "id",
    "name",
    "locked",
    "file",
    "src",
    "link",
    "tooltip",
    "animation",
    "layout",
    "workareaWidth",
    "workareaHeight",
    "videoLoadType",
    "autoplay",
    "shadow",
    "muted",
    "loop",
    "code",
    "icon",
    "userProperty",
    "trigger",
    "configuration",
    "superType",
    "points",
    "svg",
    "loadType",
  ];

